---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default: task --list

  brew:
    desc: Set up Homebrew tools
    cmd: brew bundle --file {{.ROOT_DIR}}/.config/brew/Brewfile
    sources:
      - "{{.ROOT_DIR}}/.config/brew/Brewfile"
    generates:
      - "{{.ROOT_DIR}}/.config/brew/Brewfile.lock.json"
    preconditions:
      - test -f {{.ROOT_DIR}}/.config/brew/Brewfile
      - which brew

  precommit:
    desc: add pre-commit hooks
    cmd: uvx pre-commit install
    generates:
      - "{{.ROOT_DIR}}/.git/hooks/pre-commit"
    preconditions:
      - which uvx
      
  run-once:
    desc: commands to be ran once (e.g. theming)
    run: once
    cmds:
      - curl https://raw.githubusercontent.com/catppuccin/fzf/refs/heads/main/themes/catppuccin-fzf-macchiato.fish | fish
      - yes | fish_config theme save "Catppuccin Macchiato"
    preconditions:
      - which fish

  stow:
    desc: Link files to .config
    cmd: stow -t $HOME .
    preconditions:
      - which stow
