---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default: task --list

  brew:
    desc: Set up Homebrew tools
    cmd: brew bundle --file {{.ROOT_DIR}}/.config/brew/Brewfile
    sources:
      - "{{.ROOT_DIR}}/.config/brew/Brewfile"
    preconditions:
      - test -f {{.ROOT_DIR}}/.config/brew/Brewfile
      - which brew

  precommit:
    desc: add pre-commit hooks
    cmd: uvx pre-commit install
    generates:
      - "{{.ROOT_DIR}}/.git/hooks/pre-commit"
    preconditions:
      - which uvx

  run-once:
    desc: commands to be ran once (e.g. theming)
    run: once
    deps:
      - brew
    cmds:
      - touch ~/.hushlogin
      - fish -c "fisher update"
      - curl https://raw.githubusercontent.com/catppuccin/fzf/refs/heads/main/themes/catppuccin-fzf-macchiato.fish | fish
      - fish -c "yes | fish_config theme save 'Catppuccin Macchiato'"
      - mkdir -p "$(bat --config-dir)/themes"
      - curl -fsSL https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Macchiato.tmTheme -o "$(bat --config-dir)/themes/Catppuccin Macchiato.tmTheme"
      - curl -fsSL https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Latte.tmTheme -o "$(bat --config-dir)/themes/Catppuccin Latte.tmTheme"
      - curl -fsSL https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Frappe.tmTheme -o "$(bat --config-dir)/themes/Catppuccin Frappe.tmTheme"
      - curl -fsSL https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme -o "$(bat --config-dir)/themes/Catppuccin Mocha.tmTheme"
      - bat cache --build
      - $HOMEBREW_PREFIX/opt/tpm/share/tpm/bin/install_plugins
    preconditions:
      - which fish

  stow:
    desc: Link files to .config
    cmd: stow -t $HOME .
    preconditions:
      - which stow
